Description: 
  Challenge 1 - Create an EC2 instance in a given VPC

Parameters:
  myVPC:
    Description: vpc used for ec2 instance
    Type: AWS::EC2::VPC::Id

  PublicSubnet:
    Description: Public subnet used for ec2 instance
    Type: AWS::EC2::Subnet::Id

  AMItoUse:
    Description: Image Id for Amazon linux 2
    Type: AWS::EC2::Image::Id


Resources:
  WebAccessSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: allows inbound access on TCP port 80
      SecurityGroupIngress:
       - IpProtocol: tcp
         FromPort: 80
         ToPort: 80
         CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: "-1"
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
      VpcId: !Ref myVPC
    
  WebSecureServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AMItoUse
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          GroupSet:
          - !Ref "WebAccessSecurityGroup"
          SubnetId:
            !Ref PublicSubnet
          DeviceIndex: "0"
    
      InstanceType: t3.micro
      UserData: 
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo yum update -y
          sudo yum install -y httpd
          sudo systemctl start httpd
          sudo systemctl enable httpd