Description: >
  Jeffrey / Udacity 2023

Parameters:
  EnviroName:
    Description: This is the name of the current environment
    Type: String

  MyLaunchTemplateVersionNumber:
    Type: String
    Default: '1'

Resources:
  LBSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to our loadbalancer
      VpcId:
        Fn::ImportValue:
          !Sub ${EnviroName}-VPCID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub ${EnviroName} Load balancer SG
  WebServerSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow requesst to web server
      VpcId:
        Fn::ImportValue:
          !Sub ${EnviroName}-VPCID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub ${EnviroName} Web Server SG

  WebAppLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: WebAppLaunchTemplate
      LaunchTemplateData: 
        ImageId: ami-0b5eea76982371e91
        InstanceType: t2.micro
        KeyName: FulcrumKey
        SecurityGroupIds:
          - Ref: WebServerSecGroup
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            sudo yum update -y
            sudo yum install -y httpd
            sudo systemctl start httpd
            sudo systemctl enable httpd
            cd /var/www/html
            echo "Udacity Demo Web Server Up and Running!" > index.html
        BlockDeviceMappings:
          - DeviceName: "/dev/sdk"
            Ebs:
              VolumeSize: 10
              
  WebAppGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier: 
      - Fn::ImportValue:
          !Sub ${EnviroName}-PRV-SNETS
      LaunchTemplate:
        LaunchTemplateId: !Ref WebAppLaunchTemplate
        Version: !Ref MyLaunchTemplateVersionNumber
      MaxSize: '4'
      MinSize: '2'
      TargetGroupARNs:
        - Ref: WebAppTargetGroup
      Tags:
        - Key: Name
          Value: !Sub ${EnviroName} ASG
          PropagateAtLaunch: true

  ImWebAppLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      SecurityGroups:
        - Ref: LBSecGroup
      Subnets:
        - Fn::ImportValue: !Sub ${EnviroName}-PUB1-NET
        - Fn::ImportValue: !Sub ${EnviroName}-PUB2-NET

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions: 
      - Type: forward
        TargetGroupArn: !Ref WebAppTargetGroup
      LoadBalancerArn: !Ref WebAppLoadBalancer 
      Port: 80
      Protocol: HTTP
  

  ALBListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions: 
      - Type: forward
        TargetGroupArn: !Ref WebAppTargetGroup
      Conditions: 
      - Field: path-pattern
        Values: [/]
      ListenerArn: !Re Listener 
      Priority: 1 

  WebAppTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 8
      HealthyThresholdCount: 2
      Port: 8080
      Protocol: HTTP
      UnhealthyThresholdCount: 5
      VpcId: 
        Fn::ImportValue:
          !Sub ${EnviroName}-VPCID

  launchConfigName:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      LaunchConfigurationName: 
      AssociatePublicIpAddress: true|false
      IamInstanceProfile: #InstanceProfile
      ImageId: 
      InstanceType: 
      KeyName: 
      SecurityGroups:
        - sg-id
      UserData:
        Fn::Base64: !Sub
          #!/bin/bash -ex # your script here
